server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingsystem_ratingservice
    username: root
    password: 1234
  application:
    name: RATING-SERVICE
  config:
    import:
    - configserver:http://localhost:8084

  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active:
    - dev
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka